# Generated by Django 3.2.9 on 2021-11-24 18:11

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('designation', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=62, unique=True)),
                ('aadhar_id', models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(14)])),
                ('pancard_id', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('location', models.TextField(max_length=500)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('passing_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=50)),
                ('linkedin', models.URLField(blank=True, max_length=50, verbose_name='LinkedIn URL')),
                ('facebook', models.URLField(blank=True, max_length=50, verbose_name='Facebook URL')),
                ('instagram_id', models.CharField(blank=True, max_length=50, verbose_name='Instagram ID')),
                ('industry', models.CharField(blank=True, max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(max_length=35)),
                ('zipcode', models.CharField(max_length=12, validators=[django.core.validators.MinValueValidator(5)])),
                ('key_skills', models.CharField(max_length=50)),
                ('total_exp', models.PositiveSmallIntegerField(verbose_name='Total Experience')),
                ('years_in_business', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cin_no', models.CharField(blank=True, max_length=21, validators=[django.core.validators.MinValueValidator(21), django.core.validators.MaxValueValidator(21)], verbose_name='CIN NO')),
                ('turnover', models.CharField(blank=True, max_length=30)),
                ('date_of_incorporation', models.DateField(blank=True, null=True)),
                ('employees', models.PositiveIntegerField(blank=True, null=True)),
                ('ctc', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('next_act', models.CharField(blank=True, max_length=100)),
                ('udf01', models.CharField(blank=True, max_length=100)),
                ('udf02', models.CharField(blank=True, max_length=100)),
                ('udf03', models.CharField(blank=True, max_length=100)),
                ('udf04', models.CharField(blank=True, max_length=100)),
                ('udf05', models.CharField(blank=True, max_length=100)),
                ('udf06', models.CharField(blank=True, max_length=100)),
                ('udf07', models.CharField(blank=True, max_length=100)),
                ('udf08', models.CharField(blank=True, max_length=100)),
                ('udf09', models.CharField(blank=True, max_length=100)),
                ('udf10', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='.', validators=[django.core.validators.FileExtensionValidator(['csv', 'xlsx', 'xls'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
