# Generated by Django 3.2.9 on 2021-11-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='upload_dir',
            new_name='upload_file',
        ),
    ]
