# Generated by Django 3.2.9 on 2021-11-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_turnoveranewleaf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=62, primary_key=True, serialize=False),
        ),
    ]
