# Generated by Django 3.2.9 on 2021-11-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_addeddefaultval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='date_of_incorporation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='passing_year',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='years_in_business',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
