# Generated by Django 3.2.9 on 2021-11-25 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20211125_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='aadhar_id',
            field=models.CharField(blank=True, default='', max_length=15, unique=True, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='cin_no',
            field=models.CharField(blank=True, default='', max_length=21, validators=[django.core.validators.MinValueValidator(21), django.core.validators.MaxValueValidator(21)], verbose_name='CIN NO'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='college',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='degree',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='department',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook',
            field=models.URLField(blank=True, default='', max_length=50, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Instagram ID'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedin',
            field=models.URLField(blank=True, default='', max_length=50, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='location',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='next_act',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='pancard_id',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='turnover',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='udf01',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='udf02',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='udf03',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='udf04',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='udf05',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='udf06',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='udf07',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='udf08',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='udf09',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='udf10',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='university',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='years_in_business',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
