# Generated by Django 3.2.9 on 2021-11-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20211125_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='date_of_incorporation',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
