# Generated by Django 3.2.9 on 2021-11-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contactinfo_date_of_incorporation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='employees',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='total_exp',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Experience'),
        ),
    ]
