# Generated by Django 3.2.9 on 2021-11-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20211125_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='ctc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='employees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='total_exp',
            field=models.IntegerField(default=0, verbose_name='Total Experience'),
        ),
    ]
