# Generated by Django 3.2.9 on 2021-11-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20211125_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='employees',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
