# Generated by Django 3.2.9 on 2021-11-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20211125_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='employees',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
