# Generated by Django 3.2.9 on 2021-11-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_alter_contactinfo_ctc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='total_exp',
            field=models.CharField(default='', max_length=15, verbose_name='Total Experience'),
        ),
    ]
