# Generated by Django 3.2.9 on 2021-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_alter_contactinfo_total_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='segment',
            field=models.CharField(blank=True, default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='sub_segment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
