# Generated by Django 3.2.9 on 2021-12-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_auto_20211214_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='aadhar_id',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='cin_no',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='CIN NO'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='zipcode',
            field=models.CharField(max_length=12),
        ),
    ]
