# Generated by Django 3.2.9 on 2021-12-30 16:46

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20211220_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='India', max_length=2),
        ),
    ]
