# Generated by Django 3.2.9 on 2021-12-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_turnoveranewleaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
