# Generated by Django 3.2.9 on 2021-11-20 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_username_newuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='newuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
