# Generated by Django 3.2.9 on 2021-11-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_deletedfirst_namefield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
