# Generated by Django 3.2.9 on 2021-12-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funnel_name', models.CharField(max_length=60)),
                ('segment_name', models.CharField(default='General', max_length=60)),
                ('sub_segment_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('frequency', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
