# Generated by Django 3.2.9 on 2021-12-05 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funnels.defaulttemplates'),
        ),
    ]
