# Generated by Django 3.2.9 on 2021-12-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0002_sequence_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnel',
            name='no_of_seq',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
