# Generated by Django 3.2.9 on 2021-12-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0003_funnel_no_of_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='funnel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funnels.funnel'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
