# Generated by Django 3.2.9 on 2021-12-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0004_auto_20211207_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnel',
            name='start_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
