# Generated by Django 3.2.9 on 2021-12-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0007_auto_20211221_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnel',
            name='ongoing',
            field=models.CharField(choices=[('D', 'Draft'), ('O', 'Ongoing'), ('C', 'Completed')], default='D', max_length=20),
        ),
    ]
