# Generated by Django 3.2.9 on 2021-12-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0009_alter_funnel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnel',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
