# Generated by Django 3.2.9 on 2021-12-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0010_alter_funnel_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='sch_date',
            field=models.DateField(null=True),
        ),
    ]
