# Generated by Django 3.2.9 on 2021-12-22 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0011_sequence_sch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnel',
            name='seqs_remaining',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='funnel',
            name='sub_segment',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
