# Generated by Django 3.2.9 on 2021-12-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0012_auto_20211222_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funnel',
            old_name='ongoing',
            new_name='status',
        ),
    ]
